version: "3.8"
services:
  docker-apache:
    image: my-php-site:latest
    container_name: docker-apache
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: badcrud
    ports:
      - "3306:3306"
    volumes:
      - ./db/badcrud.sql:/docker-entrypoint-initdb.d/badcrud.sql:ro


  zap:
    image: owasp/zap2docker-weekly
    container_name: zap-container
    command: ["zap.sh", "-daemon", "-port", "8090", "-host", "0.0.0.0", "-config", "api.disablekey=true"]
    ports:
      - "8090:8090"
    depends_on:
      - docker-apache
    networks:
      - default

networks:
  default:
    external:
      name: bridge